title: Syrena Law

url: https://syrena-law.github.io
baseurl: ''
port: 8666
permalink: /:title/
encoding: utf-8

# Build settings
markdown: kramdown
include: ['_pages']
exclude: [.git, .gitignore, .sass-cache, README.md, jekyllbuild]


defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

# prose.io
prose:
  media: 'img/portfolio'
  ignore:
    - .gitignore
    - _config.yml
    - _layouts
    - _includes
    - _plugins
    - css
    - js
    - CNAME
    - index.html
    - img/favicons
    - img/swipebox
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "title"
        field:
          element: "text"
          label: "nome do projeto"
      - name: "subtitle"
        field:
          element: "text"
          label: "subtitulo do projeto"
      - name: "img"
        field:
          element: "text"
          label: "imagem de capa para o projeto"
          placeholder: "roundicons.png"
