title: Syrena Law

url: https://syrena-law.github.io
baseurl: ''
port: 8666
permalink: /:title/
encoding: utf-8

# Build settings
markdown: kramdown
include: ['_pages']
exclude: [.git, .gitignore, .sass-cache, README.md, jekyllbuild]


defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# prose.io
prose:
  media: 'img/portfolio'
  ignore:
    - .gitignore
    - _config.yml
    - _layouts
    - _includes
    - _plugins
    - css
    - js
    - CNAME
    - index.html
    - img/favicons
    - img/swipebox
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "title"
        field:
          element: "text"
          label: "post title"
      - name: "cover"
        field:
          element: "text"
          label: "cover image for post"
          placeholder: "img/posts/photo00.jpg"
